/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as ShellAgentsIndexRouteImport } from './routes/_shell.agents.index'
import { Route as ShellAgentsAgentIdRouteImport } from './routes/_shell.agents.$agentId'
import { Route as ShellCustomersIndexRouteImport } from './routes/_shell.customers.index'
import { Route as ShellCustomersCustomerIdRouteImport } from './routes/_shell.customers.$customerId'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAgentsIndexRoute = ShellAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAgentsAgentIdRoute = ShellAgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCustomersIndexRoute = ShellCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCustomersCustomerIdRoute =
  ShellCustomersCustomerIdRouteImport.update({
    id: '/customers/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => ShellRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/login': typeof LoginRoute
  '/agents/$agentId': typeof ShellAgentsAgentIdRoute
  '/customers/$customerId': typeof ShellCustomersCustomerIdRoute
  '/agents/': typeof ShellAgentsIndexRoute
  '/customers/': typeof ShellCustomersIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof ShellIndexRoute
  '/agents/$agentId': typeof ShellAgentsAgentIdRoute
  '/customers/$customerId': typeof ShellCustomersCustomerIdRoute
  '/agents': typeof ShellAgentsIndexRoute
  '/customers': typeof ShellCustomersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/agents/$agentId': typeof ShellAgentsAgentIdRoute
  '/_shell/customers/$customerId': typeof ShellCustomersCustomerIdRoute
  '/_shell/agents/': typeof ShellAgentsIndexRoute
  '/_shell/customers/': typeof ShellCustomersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/agents/$agentId'
    | '/customers/$customerId'
    | '/agents/'
    | '/customers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/agents/$agentId'
    | '/customers/$customerId'
    | '/agents'
    | '/customers'
  id:
    | '__root__'
    | '/_shell'
    | '/login'
    | '/_shell/'
    | '/_shell/agents/$agentId'
    | '/_shell/customers/$customerId'
    | '/_shell/agents/'
    | '/_shell/customers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/agents/': {
      id: '/_shell/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof ShellAgentsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/agents/$agentId': {
      id: '/_shell/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof ShellAgentsAgentIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/customers/': {
      id: '/_shell/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof ShellCustomersIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/customers/$customerId': {
      id: '/_shell/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof ShellCustomersCustomerIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellIndexRoute: typeof ShellIndexRoute
  ShellAgentsAgentIdRoute: typeof ShellAgentsAgentIdRoute
  ShellCustomersCustomerIdRoute: typeof ShellCustomersCustomerIdRoute
  ShellAgentsIndexRoute: typeof ShellAgentsIndexRoute
  ShellCustomersIndexRoute: typeof ShellCustomersIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellIndexRoute: ShellIndexRoute,
  ShellAgentsAgentIdRoute: ShellAgentsAgentIdRoute,
  ShellCustomersCustomerIdRoute: ShellCustomersCustomerIdRoute,
  ShellAgentsIndexRoute: ShellAgentsIndexRoute,
  ShellCustomersIndexRoute: ShellCustomersIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
